### ISSUE TITLE
Error generating ffjson files.

### ISSUE THREAD

**Issue by ortuman** [pquerna/ffjson#166] opened 2016-02-16 16:24 UTC
Hi, i'm getting the following error when trying to generate the ffjson intermediate files.

Error: error=Could not find source directory: GOPATH=["/Users/miguelangelortunoortuno/golang"] REL="/Users/miguelangelortunoortuno/golang" path="":

Any help?

Thank you!

**Comment by ortuman** [comment] 2016-02-16 16:56
Getting this error now... :(

Error: Go Run Failed for: /var/folders/_s/_kjy0pds16z44fwd6f498gdr0000gn/T/ffjson-inception359608853.go
STDOUT:

STDERR:
/var/folders/_s/_kjy0pds16z44fwd6f498gdr0000gn/T/ffjson-inception359608853.go:8:2: import "github.com/Hooks-Alerts/mercury" is a program, not an importable package

**Comment by pquerna** [comment] 2016-02-16 17:12
Duplicate of https://github.com/pquerna/ffjson/issues/157 -- `main` packages aren't currently supported, because the method we use to extract structs can't be used.

**Closed** 2016-02-16 18:46 UTC
