### ISSUE TITLE
Can add skip Unmarshup?

### ISSUE THREAD

**Issue by smithfox** [pquerna/ffjson#52] opened 2015-01-20 02:01 UTC
Most of query service, just only need marshup.

**Comment by klauspost** [comment] 2015-02-03 12:58
Duplicate of #43 ?

**Comment by klauspost** [comment] 2015-02-06 15:43
Added proposal as PR #70

**Comment by pquerna** [comment] 2015-02-06 15:50
#70 is merged, thanks!

**Closed by pquerna** 2015-02-06 15:50 UTC
